server:
  port: 8090
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  #    show-sql: true
  config:
    import: "configserver:http://configserver-ms:8071/"
  application:
    name: "loans"

  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:loansdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver-ms:8070/eureka/
    fetch-registry: true
    register-with-eureka: true

info:
  app:
    name: "loans"
    description: "learn API for loans"
    version: "1.1.0"

logging:
  level:
    com:
      learn:
        loans: DEBUG